### ISSUE TITLE
Poor model fit.

### ISSUE THREAD

**Issue by jabienias** [hpparvi/PyTransit#158]
I have been using pytransit 2.6.4 to model various transits and have obtained good results, except for one light curve where the model produces a very poor fit. I am using exactly the same code as the other transits. The corner plots look very odd and t23 comes out as "nan"

It is also notable that sample_mcmc runs very quickly, taking about 5 minutes, while the other light curves require about 15 minutes.

**Screenshots**
I am attaching a pdf of the complete notebook so you can see the process. It also includes a manual fit which gives me realistic results.

**Desktop (please complete the following information):**
 - Windows 11 WSL
 - Chrome 

[bad_fit.pdf](https://github.com/hpparvi/PyTransit/files/15307279/bad_fit.pdf)

**Comment by hpparvi** [comment]
Hi John,

The bad fit is because the stellar density has a default uniform prior from 0.1 to 25 g/cm^3, and the manual parameters you set in 191 are p = 1.0 days and a = 17.6 R_star, which correspond to a stellar density of ~105 g/cm^3. So, the optimizer can never reach the high stellar density due to the prior. Try adjusting the rho prior and you should get a fine fit.

Cheers,
Hannu

**Comment by jabienias** [comment]
Many thanks, Hannu. That's fixed it for me (again).
Cheers
John
